### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by bhj** [mathieudutour/redux-throttle#4]
Hi and thanks for this middleware, it's super useful in my [app](https://github.com/bhj/karaoke-forever).

I know the license is specified in `package.json`, but if a LICENSE file could be added, that would appease tools like (in my case) license-webpack-plugin which want a file /w copyright that can be appended to the others. Thanks again.

**Comment by mathieudutour** [comment]
Cool app 👍 

Added the license

**Comment by bhj** [comment]
Thanks @mathieudutour, if you get a moment to bump the npm package, that would be awesome as well.

**Comment by bhj** [comment]
@mathieudutour Bump for publishing the package with the LICENSE included :)

```
WARNING in license-webpack-plugin: could not find any license file for redux-throttle.
```
