### ISSUE TITLE
Need an action to empty throttled

### ISSUE THREAD

**Issue by Ryuurock** [mathieudutour/redux-throttle#5]
When the store is re-created, dispatch has been updated, lodash.throttle caches the dispatch function, causing the component to no longer respond to updates after remounting, So we need an action to empty throttled

**Comment by mathieudutour** [comment]
I don't think recreating the store is something you should do?

**Comment by Ryuurock** [comment]
https://codesandbox.io/s/great-rgb-86yfi

**Comment by mathieudutour** [comment]
I don't think you should do that - but if you want to, recreate the middleware as the same time as the store.

I don't think throwing away the throttled actions is something you should to (instead you should cancel the existing ones before your store is destroyed like this: https://codesandbox.io/s/magical-night-mfuvb)
